name: Build and Deploy gohey-san app to Firebase

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run build
      env:
        REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
        REACT_APP_LIFF_ID: ${{ vars.REACT_APP_LIFF_ID }}
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "{{ secrets.FIREBASE_SERVICE_ACCOUNT_GOHEY_SAN }}"
        projectId: gohey-san
        channelId: "live"
